# Generated by Django 5.2.8 on 2025-11-07 06:44

import django.db.models.deletion
import django.utils.timezone
import fitquest.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitquest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', fitquest.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30, verbose_name='소셜 제공자')),
                ('provider_user_id', models.CharField(max_length=128, verbose_name='소셜 사용자 ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='소셜 이메일')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='소셜 닉네임')),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='연동 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '소셜 계정',
                'verbose_name_plural': '소셜 계정',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
