# Generated by Django 5.2.8 on 2026-03-21 18:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_exercise_runningsession_current_pace_min_per_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward_title', models.CharField(blank=True, max_length=50, null=True)),
                ('reward_exp', models.IntegerField(default=0)),
                ('metric', models.CharField(max_length=50)),
                ('target_value', models.FloatField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userquestprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exerciselog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='reward_points',
        ),
        migrations.RemoveField(
            model_name='runningsession',
            name='avg_pace_min_per_km',
        ),
        migrations.RemoveField(
            model_name='runningsession',
            name='current_pace_min_per_km',
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='calories_per_minute',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='calories_burned',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quest',
            name='metric',
            field=models.CharField(default='distance', max_length=50),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quest',
            name='reward_xp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='quest',
            name='target_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='runningsession',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='runningsession',
            name='distance_km',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='runningsession',
            name='duration_sec',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userquestprogress',
            name='cycle_key',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='userquestprogress',
            name='completed_at',
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
