# Generated by Django 6.0.3 on 2026-03-23 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_achievement_alter_userquestprogress_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('stretching', '스트레칭'), ('cardio', '유산소'), ('strength', '근력')], max_length=20)),
                ('target_muscle', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('equipment', models.CharField(default='맨몸', max_length=50)),
                ('duration_or_reps', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(default='일반', max_length=50),
        ),
        migrations.AddField(
            model_name='exerciselog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='runningsession',
            name='avg_pace_min_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='runningsession',
            name='current_pace_min_per_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userquestprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quest',
            name='metric',
            field=models.CharField(choices=[('distance', 'Distance'), ('duration', 'Duration'), ('calories', 'Calories')], default='distance', max_length=50),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='runningsession',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='userquestprogress',
            unique_together={('user', 'quest', 'cycle_key')},
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.workout')),
            ],
        ),
    ]
