# Generated by Django 6.0.3 on 2026-03-26 23:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_workout_exercise_category_exerciselog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='calories_per_minute',
            field=models.IntegerField(default=0, help_text='분당 소모 칼로리'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='calories_burned',
            field=models.IntegerField(default=0, help_text='소모 칼로리'),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='duration_minutes',
            field=models.IntegerField(default=0, help_text='운동 시간(분)'),
        ),
    ]
