# Generated by Django 5.2.8 on 2025-11-06 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_sec', models.IntegerField()),
                ('avg_pace_min_per_km', models.DecimalField(decimal_places=2, max_digits=4)),
                ('current_pace_min_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
