# Generated by Django 5.2.8 on 2025-11-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_type', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], max_length=10)),
                ('quest_name', models.CharField(max_length=100)),
                ('quest_description', models.CharField(max_length=255)),
                ('exp', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('streak_days', models.IntegerField(default=0)),
            ],
        ),
    ]
