# Generated by Django 5.2.7 on 2026-01-06 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_quest_userquestprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestprogress',
            name='cycle_key',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userquestprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='userquestprogress',
            unique_together={('user', 'quest', 'cycle_key')},
        ),
    ]
