# Generated by Django 5.2.7 on 2026-01-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_userquestprogress_cycle_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runningsession',
            name='current_pace_min_per_km',
        ),
        migrations.AddField(
            model_name='quest',
            name='metric',
            field=models.CharField(choices=[('distance', 'Distance (km)'), ('duration', 'Duration (min)'), ('calories', 'Calories (kcal)')], default='distance', max_length=10),
        ),
        migrations.AlterField(
            model_name='runningsession',
            name='avg_pace_min_per_km',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='runningsession',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
    ]
