# Generated by Django 5.2.7 on 2026-01-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitquest', '0003_customuser_exp_customuser_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
