# Generated by Django 6.0.3 on 2026-03-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitquest', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
