# Generated by Django 6.0.3 on 2026-03-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitquest', '0005_customuser_current_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monster_tier',
            field=models.CharField(default='bronze', max_length=20),
        ),
    ]
