services:
  db:
    image: mysql:8.0
    container_name: fitquest_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fitquest
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=rootpass
    ports:
      - "3307:3306"

  web:
    build: .
    container_name: fitquest_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=fitquest
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_HOST=db
    depends_on:
      - db

volumes:
  mysql_data: