name: Deploy Backend

on:
  push:
    branches:
      - backend-final

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull latest code
        uses: actions/checkout@v3

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ 43.203.52.243 }} "
            cd /home/ubuntu/app &&
            git pull &&
            docker compose down &&
            docker compose up -d --build
          "
