# Generated by Django 5.2.8 on 2025-11-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitquest', '0002_alter_customuser_managers_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
